// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBzYmJXDkxlRre-w64-irN2qhzZldG_kk',
    appId: '1:757936243481:web:b5a2185d46fea5e5f2bb88',
    messagingSenderId: '757936243481',
    projectId: 'pillpall-8b3c4',
    authDomain: 'pillpall-8b3c4.firebaseapp.com',
    storageBucket: 'pillpall-8b3c4.firebasestorage.app',
    measurementId: 'G-BYVRS3K61N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWx5n0_Lo_-_VRTtOHtO4DFbt5OcdguEs',
    appId: '1:757936243481:android:c37d686ed74212bbf2bb88',
    messagingSenderId: '757936243481',
    projectId: 'pillpall-8b3c4',
    storageBucket: 'pillpall-8b3c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzm4w3fGIGj8v7Qz5Rj1DbQCjUFFUsFFU',
    appId: '1:757936243481:ios:9247f4cf258ee8adf2bb88',
    messagingSenderId: '757936243481',
    projectId: 'pillpall-8b3c4',
    storageBucket: 'pillpall-8b3c4.firebasestorage.app',
    iosBundleId: 'com.company.pillpall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzm4w3fGIGj8v7Qz5Rj1DbQCjUFFUsFFU',
    appId: '1:757936243481:ios:0bcb360d42d80ec7f2bb88',
    messagingSenderId: '757936243481',
    projectId: 'pillpall-8b3c4',
    storageBucket: 'pillpall-8b3c4.firebasestorage.app',
    iosBundleId: 'com.example.pillpall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBzYmJXDkxlRre-w64-irN2qhzZldG_kk',
    appId: '1:757936243481:web:1729dc456155f65ef2bb88',
    messagingSenderId: '757936243481',
    projectId: 'pillpall-8b3c4',
    authDomain: 'pillpall-8b3c4.firebaseapp.com',
    storageBucket: 'pillpall-8b3c4.firebasestorage.app',
    measurementId: 'G-52LHERXQNZ',
  );
}
